// API functions (direct async calls)
export {
  // Categories
  fetchCategories,
  fetchCategoryById,
  createCategory,
  updateCategory,
  deleteCategory,
  // Subcategories
  fetchSubcategoriesByCategory,
  createSubcategory,
  updateSubcategory,
  deleteSubcategory,
  // Quizzes
  fetchQuizzes,
  fetchQuizById,
  createQuiz,
  updateQuiz,
  deleteQuiz,
  // Quiz Attempts
  startQuizAttempt,
  submitQuizAttempt,
  startQuestion,
  getMyQuizAttempts,
  getAllUsersQuizAttempts,
  getAttemptDetails,
  // Questions
  fetchQuestions,
  createQuestion,
  updateQuestion,
  deleteQuestion,
  // Departments/Branches/Teams
  fetchDepartments,
  fetchDepartmentById,
  fetchBranchesByDepartment,
  fetchBranchesForDepartments,
  fetchQuizBranchesByDepartment,
  fetchQuizBranchesForDepartments,
  fetchBranchById,
  fetchTeamsByBranch,
  fetchTeamsForBranches,
  fetchTeamById,
} from './quizApi';

// Redux Thunk Actions (for dispatch)
export {
  fetchCategories as fetchCategoriesThunk,
  fetchCategoryById as fetchCategoryByIdThunk,
  createCategory as createCategoryThunk,
  updateCategory as updateCategoryThunk,
  deleteCategory as deleteCategoryThunk,
  fetchSubcategoriesByCategory as fetchSubcategoriesByCategoryThunk,
  createSubcategory as createSubcategoryThunk,
  updateSubcategory as updateSubcategoryThunk,
  deleteSubcategory as deleteSubcategoryThunk,
  fetchQuizzes as fetchQuizzesThunk,
  fetchQuizById as fetchQuizByIdThunk,
  createQuiz as createQuizThunk,
  updateQuiz as updateQuizThunk,
  deleteQuiz as deleteQuizThunk,
  startQuizAttempt as startQuizAttemptThunk,
  submitQuizAttempt as submitQuizAttemptThunk,
  startQuestion as startQuestionThunk,
  getMyQuizAttempts as getMyQuizAttemptsThunk,
  getAllUsersQuizAttempts as getAllUsersQuizAttemptsThunk,
  fetchQuestions as fetchQuestionsThunk,
  createQuestion as createQuestionThunk,
  updateQuestion as updateQuestionThunk,
  deleteQuestion as deleteQuestionThunk,
} from './quizActions';

// Slice actions and selectors
export {
  resetSaveStatus,
  resetDeleteStatus,
  resetCurrentCategory,
  resetCurrentQuiz,
  resetCurrentAttempt,
  resetQuizResult,
  clearQuizErrors,
  // Selectors
  selectCategories,
  selectCurrentCategory,
  selectCategoriesLoading,
  selectCategoriesError,
  selectSubcategories,
  selectSubcategoriesLoading,
  selectSubcategoriesError,
  selectQuizzes,
  selectCurrentQuiz,
  selectSubcategoryName,
  selectQuizzesLoading,
  selectQuizzesError,
  selectQuestions,
  selectQuestionsLoading,
  selectQuestionsError,
  selectCurrentAttempt,
  selectMyAttempts,
  selectAllUsersAttempts,
  selectAttemptsLoading,
  selectAttemptsError,
  selectQuizResult,
  selectSaveLoading,
  selectSaveError,
  selectSaveSuccess,
  selectDeleteLoading,
  selectDeleteError,
  selectDeleteSuccess,
} from './quizSlice';

// Reducer
export { default as quizReducer } from './quizSlice';
